local L = LibStub("AceLocale-3.0"):NewLocale("Memento", "deDE")

if not L then return end

L["info"] = "Info"

L["info.description"] = "Beschreibung"
L["info.description.content_1"] = "Memento ist ein Addon, welches bei bestimmten Events automatisch Screenshots erstellt. Die folgenden Events werden aktuell unterstützt (weitere sind geplant):\n\n"
                                .. "  • |cfff2e699Erfolge|r (persönliche Erfolge, sowie erreichte Erfolgskriterien und Gildenerfolge)*\n"
                                .. "  • |cfff2e699Bosskampf|r (Sieg und Niderlage)\n"
                                .. "  • |cfff2e699Levelaufstieg|r\n"
                                .. "  • |cfff2e699Spielertod|r\n"
                                .. "  • |cfff2e699Duell beendet|r\n"
                                .. "  • |cfff2e699Spielerlogin|r\n\n"
L["info.description.content_2"] = "* Erfolge gibt es in 'Classic' nicht"
L["info.about"] = "Über"
L["info.about.addon-version"] = "Addonversion"
L["info.about.game-version"] = "Spielversion"
L["info.about.author"] = "Autor"
L["info.about.feedback"] = "Um Fehler zu melden oder Feedback zum Addon zu geben, nutze bitte eine der folgenden Möglichkeiten."
L["info.about.email.name"] = "E-Mail"
L["info.about.email.desc"] = "Öffnet ein Popup-Fenster mit einer E-Mailadresse."
L["info.about.email.popup"] = "Um die E-Mail zu kopieren drücke STRG + C."
L["info.about.github.name"] = "Github"
L["info.about.github.desc"] = "Öffnet ein Popup-Fenster mit einem Link nach Github."
L["info.about.github.popup"] = "Um den Link zu kopieren drücke STRG + C."

L["options"] = "Einstellungen"
L["options.general"] = "allgemeine Einstellungen"
L["options.general.notification.name"] = "Chatbenachrichtigung"
L["options.general.notification.desc"] = "Aktiviere oder deaktiviere die Benachrichtung im Chat, wenn ein Screenshot erstellt wurde."
L["options.general.statistic.name"] = "Statistikausgabe"
L["options.general.statistic.desc"] = "Aktiviere oder deaktiviere die Statistikausgabe im Chat, nach dem Login."
L["options.general.ui.name"] = "Benutzeroberfläche für den Screenshot ausblenden |T132049:0|t"
L["options.general.ui.desc"] = "Aktiviere oder deaktiviere die Option, dass die Benutzeroberfläche für den Screenshot ausgeblendet wird. Eine kleine Erfolgsanzeige wird stattdessen angezeigt.\n\n|cffffd200Hinweis:|r Während eines Kampfes kann die Benutzeroberfläche nicht automatisch ausgeblendet werden. In diesem Fall wird der Screenshot mit der Benutzeroberfläche erstellt."
L["options.general.debug.name"] = "Debugmodus"
L["options.general.debug.desc"] = "Aktiviere oder deaktiviere den Debugmodus."

L["options.event.general.active.name"] = "Screenshot für das Event '|cfff2e699%s|r' erstellen"
L["options.event.general.active.desc"] = "Aktiviere oder deaktiviere die automatische Erstellung eines Screenhots für das Event '|cfff2e699%s|r'."
L["options.event.general.delay.name"] = "Verzögerung"
L["options.event.general.delay.desc"] = "Die zeitliche Verzögerung des Screenshots, nachdem das Event '|cfff2e699%s|r' ausgelöst wurde.\n\n|cffffd200Standard:|r %d Sekunde(n)"

L["options.event.achievement"] = "Erfolge"
L["options.event.achievement.personal"] = "persönlicher Erfolg"
L["options.event.achievement.personal.exist.name"] = "Screenshot bei bereits erzieltem Erfolg erstellen"
L["options.event.achievement.personal.exist.desc"] = "Aktiviere oder deaktiviere die Erstellung eines Screenhots, wenn ein Erfolg bereits von einem anderen Charakter erlangt wurde."
L["options.event.achievement.criteria"] = "persönliches Erfolgskriterium"
L["options.event.achievement.guild"] = "Gildenerfolg"

L["options.event.encounter"] = "Bosskampf"
L["options.event.encounter.victory"] = "Bosskampf - Sieg"
L["options.event.encounter.wipe"] = "Bosskampf - Niederlage"
L["options.event.encounter.party.name"] = "Dungeon"
L["options.event.encounter.raid.name"] = "Raid"
L["options.event.encounter.scenario.name"] = "Szenario / Tiefen"

L["options.event.encounter.victory.party.desc"] = "Aktiviere oder deaktiviere die automatische Erstellung eines Screenhots, wenn ein Dungeon-Boss besiegt wurde."
L["options.event.encounter.victory.raid.desc"] = "Aktiviere oder deaktiviere die automatische Erstellung eines Screenhots, wenn ein Raid-Boss besiegt wurde."
L["options.event.encounter.victory.scenario.desc"] = "Aktiviere oder deaktiviere die automatische Erstellung eines Screenhots, wenn ein Szenario- oder Tiefen-Boss besiegt wurde."
L["options.event.encounter.victory.first.name"] = "nur der erste Sieg pro Schwierigkeit"
L["options.event.encounter.victory.first.desc"] = "Aktiviere oder deaktiviere die automatische Erstellung eines Screenhots, wenn ein Boss besiegt wurde. Diese Option gilt für jede Schwierigkeit getrennt."
L["options.event.encounter.wipe.party.desc"] = "Aktiviere oder deaktiviere die automatische Erstellung eines Screenhots, wenn bei einem Dungeon-Boss eine Niederlage stattgefunden hat."
L["options.event.encounter.wipe.raid.desc"] = "Aktiviere oder deaktiviere die automatische Erstellung eines Screenhots, wenn bei einem Raid-Boss eine Niederlage stattgefunden hat."
L["options.event.encounter.wipe.scenario.desc"] = "Aktiviere oder deaktiviere die automatische Erstellung eines Screenhots, wenn bei einem Szenario- oder Tiefen-Boss eine Niederlage stattgefunden hat."

L["options.event.levelUp"] = "Levelaufstieg"
L["options.event.death"] = "Spielertod"
L["options.event.duel"] = "Duell beendet"
L["options.event.login"] = "Spielerlogin"

L["profiles"] = "Profile"

L["statistic"] = "Statistiken"
L["statistic.screenshots"] = "Screenshots"
L["statistic.screenshots.description"] = "Diese kleine Übersicht zeigt die Anzahl aller ab Release 2.0.0 erstellten Screenshots durch Memento. In Klammern steht die Anzahl für den aktuellen Charakter."
L["statistic.screenshots.achievement.personal"] = "persönlicher Erfolg"
L["statistic.screenshots.achievement.criteria"] = "persönliches Erfolgskriterium"
L["statistic.screenshots.achievement.guild"] = "Gildenerfolg"
L["statistic.screenshots.encounter.victory"] = "Bosskampf - Sieg"
L["statistic.screenshots.encounter.wipe"] = "Bosskampf - Niederlage"
L["statistic.screenshots.levelUp"] = "Levelaufstieg"
L["statistic.screenshots.death"] = "Spielertod"
L["statistic.screenshots.duel"] = "Duel beendet"
L["statistic.screenshots.login"] = "Spielerlogin"

L["chat.event.achievement.personal.new"] = "Screenshot erstellt - persönlicher Erfolg: %s"
L["chat.event.achievement.personal.exist"] = "Screenshot erstellt - persönlicher Erfolg (wurde bereits von einem anderen Charakter erzielt): %s"
L["chat.event.achievement.criteria.new"] = "Screenshot erstellt - persönliches Erfolgskriterium für den Erfolg '%s' erhalten: %s"
L["chat.event.achievement.guild.new"] = "Screenshot erstellt - Gildenerfolg: %s"
L["chat.event.encounter.victory.new"] = "Screenshot erstellt - Bosskampf (Sieg): %s (%s)"
L["chat.event.encounter.wipe.new"] = "Screenshot erstellt - Bosskampf (Niederlage): %s (%s)"
L["chat.event.levelUp.new"] = "Screenshot erstellt - Levelaufstieg: Level %d"
L["chat.event.death.new"] = "Screenshot erstellt - Spielertod: Du bist gestorben."
L["chat.event.duel.new"] = "Screenshot erstellt - Duell beendet."
L["chat.event.login.new"] = "Screenshot erstellt - Spielerlogin."
