local L = LibStub("AceLocale-3.0"):NewLocale("Memento", "enUS", true)

L["info"] = "Info"

L["info.description"] = "Description"
L["info.description.content_1"] = "Memento is an addon that automatically takes screenshots of specific events. The following events are currently supported (more events are planned):\n\n"
                                .. "  • |cfff2e699Achievements|r (personal and guild achievements)*\n"
                                .. "  • |cfff2e699Boss fights|r (victory and wipe)\n"
                                .. "  • |cfff2e699Level-up|r\n"
                                .. "  • |cfff2e699Player death|r\n"
                                .. "  • |cfff2e699Duel finished|r\n"
                                .. "  • |cfff2e699Player login|r\n\n"
L["info.description.content_2"] = "* Achievements are not available in 'Classic'"
L["info.about"] = "About"
L["info.about.addon-version"] = "Addon version"
L["info.about.game-version"] = "Game version"
L["info.about.author"] = "Author"
L["info.about.feedback"] = "To report bugs or give feedback on the addon, please use one of the following options."
L["info.about.email.name"] = "E-Mail"
L["info.about.email.desc"] = "Opens a popup window with an e-mail address."
L["info.about.email.popup"] = "To copy the e-mail press CTRL + C."
L["info.about.github.name"] = "Github"
L["info.about.github.desc"] = "Opens a popup window with a link to Github."
L["info.about.github.popup"] = "To copy the link press CTRL + C."

L["statistic"] = "Statistics"
L["statistic.screenshots"] = "Screenshots"
L["statistic.screenshots.description"] = "This small overview shows the number of all screenshots created by Memento since release 2.0.0 The number for the current character is shown in brackets."
L["statistic.screenshots.achievement.personal"] = "Personal achievement"
L["statistic.screenshots.achievement.guild"] = "Guild achievement"
L["statistic.screenshots.encounter"] = "Boss fight"
L["statistic.screenshots.levelUp"] = "Level-up"
L["statistic.screenshots.death"] = "Player death"
L["statistic.screenshots.duel"] = "Duel finished"
L["statistic.screenshots.login"] = "Player login"

--------------- TO DO ---------------

L["options"] = "Options"

L["general.options.general"] = "General options"
L["general.options.general.notification.name"] = "Chat notification"
L["general.options.general.notification.desc"] = "Activate or deactivate the notification in the chat when a screenshot has been taken."
L["general.options.general.statistic.name"] = "Statistics output"
L["general.options.general.statistic.desc"] = "Activate or deactivate the statistics output in the chat after login."
L["general.options.general.ui.name"] = "Hide user interface for screenshot"
L["general.options.general.ui.desc"] = "Activate or deactivate the option to hide the user interface for the screenshot. A small success notification is displayed instead.\n\nNote: The user interface cannot be hidden automatically during a combat. In this case, the screenshot is taken with the user interface."

L["general.options.achievement"] = "Achievements"

L["general.options.achievement.personal"] = "Personal achievement"
L["general.options.achievement.personal.active.name"] = "Take a screenhot on personal achievement"
L["general.options.achievement.personal.active.desc"] = "Activate or deactivate the automatic creation of a screenshot when a personal achievement has been reached."
L["general.options.achievement.personal.exist.name"] = "Take a screenshot if a personal achievement has already been reached"
L["general.options.achievement.personal.exist.desc"] = "Activate or deactivate the creation of a screenshot if an personal achievement has already been reached by another character."
L["general.options.achievement.personal.timer.name"] = "Delay"
L["general.options.achievement.personal.timer.desc"] = "Time delay of the screenshot after a personal achievement has been reached.\n\nDefault: 2 seconds"

L["general.options.achievement.guild"] = "Guild achievement"
L["general.options.achievement.guild.active.name"] = "Take a screenhot on guild achievement"
L["general.options.achievement.guild.active.desc"] = "Activate or deactivate the automatic creation of a screenshot when a guild achievement has been reached."
L["general.options.achievement.guild.timer.name"] = "Delay"
L["general.options.achievement.guild.timer.desc"] = "Time delay of the screenshot after a guild achievement has been reached.\n\nDefault: 2 seconds"

L["general.options.encounter"] = "Boss fights"
L["general.options.encounter.victory.desc"] = "These options apply when defeating a boss."
L["general.options.encounter.victory.party.name"] = "Dungeon"
L["general.options.encounter.victory.party.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have killed a dungeon boss."
L["general.options.encounter.victory.raid.name"] = "Raid"
L["general.options.encounter.victory.raid.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have killed a raid boss."
L["general.options.encounter.victory.scenario.name"] = "Scenario / Delves"
L["general.options.encounter.victory.scenario.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have killed a scenario or delves boss."
L["general.options.encounter.victory.first.name"] = "only on the first kill per difficulty"
L["general.options.encounter.victory.first.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have already killed a boss. This option applies separately for each difficulty."
L["general.options.encounter.victory.timer.name"] = "Delay"
L["general.options.encounter.victory.timer.desc"] = "Time delay of the screenshot after you have killed a boss.\n\nDefault: 2 seconds"
L["general.options.encounter.wipe.desc"] = "These options apply to a wipe."
L["general.options.encounter.wipe.party.name"] = "Dungeon"
L["general.options.encounter.wipe.party.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have wiped at a dungeon boss."
L["general.options.encounter.wipe.raid.name"] = "Raid"
L["general.options.encounter.wipe.raid.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have wiped at a raid boss."
L["general.options.encounter.wipe.scenario.name"] = "Scenario / Delves"
L["general.options.encounter.wipe.scenario.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have wwiped at a scenario or delves boss."
L["general.options.encounter.wipe.timer.name"] = "Delay"
L["general.options.encounter.wipe.timer.desc"] = "Time delay of the screenshot after you have wiped.\n\nDefault: 2 seconds"

L["general.options.levelUp"] = "Level-up"
L["general.options.levelUp.active.name"] = "Take a screenhot on level-up"
L["general.options.levelUp.active.desc"] = "Activate or deactivate the automatic creation of a screenshot when a level up has taken place."
L["general.options.levelUp.timer.name"] = "Delay"
L["general.options.levelUp.timer.desc"] = "Time delay of the screenshot after a level-up has taken place.\n\nDefault: 5 seconds"

L["general.options.death"] = "Player death"
L["general.options.death.active.name"] = "Take a screenshot on player death"
L["general.options.death.active.desc"] = "Activate or deactivate the automatic creation of a screenshot when the player has died."
L["general.options.death.timer.name"] = "Delay"
L["general.options.death.timer.desc"] = "Time delay of the screenshot after the player has died.\n\nDefault: 1 second"

L["general.options.duel"] = "Duel finished"
L["general.options.duel.active.name"] = "Take a screenshot after duel"
L["general.options.duel.active.desc"] = "Activate or deactivate the automatic creation of a screenshot when a duel has ended."
L["general.options.duel.timer.name"] = "Delay"
L["general.options.duel.timer.desc"] = "Time delay of the screenshot after a duel has ended.\n\nDefault: 1 second"

L["general.options.login"] = "Player login"
L["general.options.login.active.name"] = "Take a screenshot after login"
L["general.options.login.active.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have logged in."
L["general.options.login.timer.name"] = "Delay"
L["general.options.login.timer.desc"] = "Time delay of the screenshot after you have logged in..\n\nDefault: 5 seconds"

L["general.debug"] = "Debug"

L["general.debug.general"] = "General options"
L["general.debug.general.active.name"] = "Activate debug mode"
L["general.debug.general.active.desc"] = "Activate or deactivate the debug mode."

L["profiles"] = "Profiles"

L["chat.events.achievement.personal.new"] = "Screenshot taken - Personal achievement: "
L["chat.events.achievement.personal.exist"] = "Screenshot taken - Personal achievement (has already been reached by another character): "
L["chat.events.achievement.guild.new"] = "Screenshot taken - Guild achievement: "
L["chat.events.encounter.victory.new"] = "Screenshot taken - Boss fight (Victory): "
L["chat.events.encounter.wipe.new"] = "Screenshot taken - Boss fight (Wipe): "
L["chat.events.levelUp.new"] = "Screenshot taken - Level-up: "
L["chat.events.death.new"] = "Screenshot taken - Player death: You are dead."
L["chat.events.duel.new"] = "Screenshot taken - Duel finished."
L["chat.events.login.new"] = "Screenshot taken - Player login."

L["message"] = "Screenshot taken"