local L = LibStub("AceLocale-3.0"):NewLocale("Memento", "enUS", true)

L["info"] = "Info"

L["info.description"] = "Description"
L["info.description.content_1"] = "Memento is an addon that automatically takes screenshots of specific events. The following events are currently supported (more events are planned):\n\n"
                                .. "  • |cfff2e699Achievements|r (personal achievements, as well as reached achievement criteria and guild achievements)*\n"
                                .. "  • |cfff2e699Boss fight|r (victory and wipe)\n"
                                .. "  • |cfff2e699Level-up|r\n"
                                .. "  • |cfff2e699Player death|r\n"
                                .. "  • |cfff2e699Duel finished|r\n"
                                .. "  • |cfff2e699Player login|r\n\n"
L["info.description.content_2"] = "* Achievements are not available in 'Classic'"
L["info.about"] = "About"
L["info.about.addon-version"] = "Addon version"
L["info.about.game-version"] = "Game version"
L["info.about.author"] = "Author"
L["info.about.feedback"] = "To report bugs or give feedback on the addon, please use one of the following options."
L["info.about.email.name"] = "E-Mail"
L["info.about.email.desc"] = "Opens a popup window with an e-mail address."
L["info.about.email.popup"] = "To copy the e-mail press CTRL + C."
L["info.about.github.name"] = "Github"
L["info.about.github.desc"] = "Opens a popup window with a link to Github."
L["info.about.github.popup"] = "To copy the link press CTRL + C."

L["options"] = "Options"
L["options.general"] = "General options"
L["options.general.notification.name"] = "Chat notification"
L["options.general.notification.desc"] = "Activate or deactivate the notification in the chat when a screenshot has been taken."
L["options.general.statistic.name"] = "Statistics output"
L["options.general.statistic.desc"] = "Activate or deactivate the statistics output in the chat after login."
L["options.general.ui.name"] = "Hide user interface for screenshot |T132049:0|t"
L["options.general.ui.desc"] = "Activate or deactivate the option to hide the user interface for the screenshot. A small success notification is displayed instead.\n\n|cffffd200Note:|r The user interface cannot be hidden automatically during a combat. In this case, the screenshot is taken with the user interface."
L["options.general.debug.name"] = "Debug mode"
L["options.general.debug.desc"] = "Activate or deactivate the debug mode."

L["options.event.general.active.name"] = "Take a screenshot for the '|cfff2e699%s|r' event"
L["options.event.general.active.desc"] = "Activate or deactivate the automatic creation of a screenshot for the event '|cfff2e699%s|r'."
L["options.event.general.delay.name"] = "Delay"
L["options.event.general.delay.desc"] = "The time delay of the screenshot after the event '|cfff2e699%s|r' was triggered.\n\n|cffffd200Default:|r %d second(s)"

L["options.event.achievement"] = "Achievements"
L["options.event.achievement.personal"] = "Personal achievement"
L["options.event.achievement.personal.exist.name"] = "Take a screenshot if a personal achievement has already been reached"
L["options.event.achievement.personal.exist.desc"] = "Activate or deactivate the creation of a screenshot if an personal achievement has already been reached by another character."
L["options.event.achievement.criteria"] = "Personal achievement criteria"
L["options.event.achievement.guild"] = "Guild achievement"

L["options.event.encounter"] = "Boss fight"
L["options.event.encounter.victory"] = "Boss fight - Victory"
L["options.event.encounter.wipe"] = "Boss fight - Wipe"
L["options.event.encounter.party.name"] = "Dungeon"
L["options.event.encounter.raid.name"] = "Raid"
L["options.event.encounter.scenario.name"] = "Scenario / Delve"

L["options.event.encounter.victory.party.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have killed a dungeon boss."
L["options.event.encounter.victory.raid.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have killed a raid boss."
L["options.event.encounter.victory.scenario.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have killed a scenario or delves boss."
L["options.event.encounter.victory.first.name"] = "only on the first kill per difficulty"
L["options.event.encounter.victory.first.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have already killed a boss. This option applies separately for each difficulty."
L["options.event.encounter.wipe.party.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have wiped at a dungeon boss."
L["options.event.encounter.wipe.raid.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have wiped at a raid boss."
L["options.event.encounter.wipe.scenario.desc"] = "Activate or deactivate the automatic creation of a screenshot when you have wwiped at a scenario or delves boss."

L["options.event.levelUp"] = "Level-up"
L["options.event.death"] = "Player death"
L["options.event.duel"] = "Duel finished"
L["options.event.login"] = "Player login"

L["profiles"] = "Profiles"

L["statistic"] = "Statistics"
L["statistic.screenshots"] = "Screenshots"
L["statistic.screenshots.description"] = "This small overview shows the number of all screenshots created by Memento since release 2.0.0 The number for the current character is shown in brackets."
L["statistic.screenshots.achievement.personal"] = "Personal achievement"
L["statistic.screenshots.achievement.criteria"] = "Personal achievement criteria"
L["statistic.screenshots.achievement.guild"] = "Guild achievement"
L["statistic.screenshots.encounter.victory"] = "Boss fight - Victory"
L["statistic.screenshots.encounter.wipe"] = "Boss fight - Wipe"
L["statistic.screenshots.levelUp"] = "Level-up"
L["statistic.screenshots.death"] = "Player death"
L["statistic.screenshots.duel"] = "Duel finished"
L["statistic.screenshots.login"] = "Player login"

L["chat.event.achievement.personal.new"] = "Screenshot taken - Personal achievement: %s"
L["chat.event.achievement.personal.exist"] = "Screenshot taken - Personal achievement (has already been reached by another character): %s"
L["chat.event.achievement.criteria.new"] = "Screenshot taken - Personal achievement criteria for the achievement '%s' reached: %s"
L["chat.event.achievement.guild.new"] = "Screenshot taken - Guild achievement: %s"
L["chat.event.encounter.victory.new"] = "Screenshot taken - Boss fight (Victory): %s (%s)"
L["chat.event.encounter.wipe.new"] = "Screenshot taken - Boss fight (Wipe): %s (%s)"
L["chat.event.levelUp.new"] = "Screenshot taken - Level-up: Level %d"
L["chat.event.death.new"] = "Screenshot taken - Player death: You are dead."
L["chat.event.duel.new"] = "Screenshot taken - Duel finished."
L["chat.event.login.new"] = "Screenshot taken - Player login."
