name: Package and release Memento

on:
  push:
    tags:
      - '**'

jobs:
  github-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.G_TOKEN }}  
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Github
      - name: Package and release for Github
        uses: BigWigsMods/packager@v2

