name: Package and publish Memento (Release)

on:
  push:
    branches:
      - main
    tags:
      - "*"
      - "!**-alpha**"

jobs:
  github-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.G_TOKEN }}  
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Github
      - name: Package and release for Github
        uses: BigWigsMods/packager@v2

  repository-release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # CourseForge
      - name: Package and publish for CourseForge
        uses: BigWigsMods/packager@master
        with:
          args: -p 1099991 -n "{package-name}-{project-version}{nolib}{classic}:{package-name}-{project-version}{classic}{nolib}.zip"

      # WoWInterface and Wago
      - name: Package and publish for WoWInterface and Wago
        uses: BigWigsMods/packager@master
        with:
          args: -w 26848 -a QKywRlN7
